export const menuSeedData = [
    {
    name: "BMT",
    price: 12.39,
    ingredients: "Made with pepperoni, salami, Black Forest Ham",
    image: "BMT.png",
    category: "Deli",
  },
  {
    name: "Bourbon Brisket",
    price: 15.99,
    ingredients: "Made with tangy bourbon sauce & beef",
    image: "Brisket.png",
    category: "Beef",
  },
  {
    name: "Chicken Rancher",
    price: 13.99,
    ingredients: "Fresh Rotisserie chicken with bacon and mozzarella cheese",
    image: "chicken_rancher.png",
    category: "Chicken",
  },
  {
    name: "Tuna",
    price: 13.99,
    ingredients: "Mayo mixed with fresh tuna",
    image: "tuna.png",
    category: "Fish",
  },
  {
    name: "Veggie delite",
    price: 8.99,
    ingredients: "Perfect for vegetarian, includes only cheese of your choice",
    image: "Veggie.png",
    category: "Veggie",
  },
  {
    name: "Three cheese snackwich",
    price: 3.49,
    ingredients: "Three different cheeses of your choice",
    image: "three_cheese.png",
    category: "Sidekick",
  },
  {
    name: "Teriyaki Crunch",
    price: 4.99,
    ingredients: "Teriyaki chicken mixed with sweet onion sauce",
    image: "TERIYAKI.png",
    category: "Chicken",
  },
  {
    name: "Potato Rings",
    price: 2.99,
    ingredients: "Freshly baked potato rings with Ketchup",
    image: "potato_rings.png",
    category: "Sides",
  },
  {
    name: "Nachos",
    price: 2.99,
    ingredients: "Salsa on top of Nachos",
    image: "nachos.png",
    category: "Sides",
  },
  {
    name: "M & M cookie",
    price: 1.99,
    ingredients: "Cookies with M&M candies",
    image: "m&m.png",
    category: "Sides",
  },
  {
    name: "Piri Piri Power Bowl",
    price: 2.99,
    ingredients: "Corn & beans and fresh salad",
    image: "power_bowl (1).png",
    category: "Sides",
  },
  {
    name: "Mountain Dew",
    price: 1.99,
    ingredients: "Energetic drink",
    image: "drink.png",
    category: "Drink",
  },
];